#name = input("What's your name?")
#print("\nNice to meet you {:>20}".format(name))
#print("\nNice to meet you {:<20}".format(name))
#print("\nNice to meet you {:^20}".format(name))
#print("\nNice to meet you {:=>20}".format(name))
#print("\nNice to meet you {:=<20}".format(name))
#print("\nNice to meet you {:=^20}".format(name))
#print("\nNice to meet you {:/a^20}".format(name))
value = float(input("Input a value: "))
value /= float(input("Input a value: "))
print("something", end=" > ")
print("The value is {:.2}".format(value))