value = input("Type something:")
print("="*48)
print("The primitive type of this value is:", type(value))
print("Only have space?",value.isspace())
print("Is numeric?",value.isnumeric())
print("Is alpha?",value.isalpha())
print("is alphanumeric?",value.isalnum())
print("Only upper?",value.isupper())
print("Only lower?",value.islower())
print("Is a tittle?",value.istitle())
print("="*48)